"""empty message

Revision ID: 01232594dcb1
Revises: ce40fac824b4
Create Date: 2025-06-16 02:06:56.040243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01232594dcb1'
down_revision = 'ce40fac824b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_year', sa.Integer(), nullable=True))

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('character_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('film_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('planet_id', sa.Integer(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.create_foreign_key(None, 'characters', ['character_id'], ['id'])
        batch_op.create_foreign_key(None, 'planets', ['planet_id'], ['id'])
        batch_op.create_foreign_key(None, 'films', ['film_id'], ['id'])

    with op.batch_alter_table('films', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_constraint('films_characters_fkey', type_='foreignkey')
        batch_op.drop_column('characters')

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gravity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('population', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_column('population')
        batch_op.drop_column('gravity')

    with op.batch_alter_table('films', schema=None) as batch_op:
        batch_op.add_column(sa.Column('characters', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('films_characters_fkey', 'characters', ['characters'], ['id'])
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_column('planet_id')
        batch_op.drop_column('film_id')
        batch_op.drop_column('character_id')

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('birth_year')

    # ### end Alembic commands ###
